# Generated by Django 2.2 on 2020-06-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='trade_lock',
        ),
    ]
