# Generated by Django 2.2 on 2020-06-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_remove_item_trade_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_av_week',
            field=models.FloatField(null=True),
        ),
    ]
