# Generated by Django 2.2 on 2020-06-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20200601_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(null=True)),
                ('time_q', models.DateTimeField(auto_now_add=True)),
                ('items', models.TextField(null=True)),
            ],
        ),
    ]
