# Generated by Django 3.0.6 on 2020-06-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_auto_20200605_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checker.Profile'),
        ),
    ]
