# Generated by Django 3.0.6 on 2020-06-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_auto_20200605_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
