# Generated by Django 3.0.6 on 2020-06-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='static/images/profile_def.png', null=True, upload_to=''),
        ),
    ]
