# Generated by Django 3.0.6 on 2020-06-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_auto_20200608_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='items',
        ),
        migrations.RemoveField(
            model_name='query',
            name='total_price',
        ),
        migrations.AddField(
            model_name='item',
            name='query_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checker.Query'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_def.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='steam_id64',
            field=models.CharField(default='', max_length=17, null=True),
        ),
    ]
