# Generated by Django 3.0.6 on 2020-06-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_auto_20200608_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='profile',
            new_name='profile_create',
        ),
    ]
