# Generated by Django 3.0.6 on 2020-06-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0012_auto_20200608_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='query_of',
        ),
        migrations.AddField(
            model_name='query',
            name='items',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='query',
            name='total_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='profile_create',
            field=models.CharField(default='', max_length=17, null=True),
        ),
    ]
