# Generated by Django 3.0.6 on 2020-06-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0013_auto_20200608_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'get_latest_by': 'time_q'},
        ),
    ]
