# Generated by Django 3.0.6 on 2020-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0014_auto_20200611_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend_search',
            field=models.TextField(blank=True, null=True),
        ),
    ]
